# Generated by Django 4.2.4 on 2023-08-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0004_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceticket',
            old_name='month',
            new_name='status',
        ),
    ]
